# Generated by Django 4.1.5 on 2023-01-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fooditem',
        ),
        migrations.DeleteModel(
            name='member',
        ),
        migrations.RemoveField(
            model_name='marketcost',
            name='marketcost',
        ),
        migrations.AddField(
            model_name='marketcost',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
