# Generated by Django 4.1.5 on 2023-01-21 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0003_information_delete_marketcost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information',
            old_name='item',
            new_name='fooditem',
        ),
        migrations.RenameField(
            model_name='information',
            old_name='cost',
            new_name='marketcost',
        ),
    ]
