# Generated by Django 4.1.5 on 2023-01-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0004_rename_item_information_fooditem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
