# Generated by Django 4.1.5 on 2023-01-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0005_information_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='millamaount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('meall', models.IntegerField()),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
