# Generated by Django 4.1.5 on 2023-01-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0006_millamaount'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_1', models.IntegerField(choices=[('option1', 'Option 1'), ('option2', 'Option 2'), ('option3', 'Option 3')])),
                ('choice_2', models.IntegerField(choices=[('option1', 'Option 1'), ('option2', 'Option 2'), ('option3', 'Option 3')])),
                ('choice_3', models.IntegerField(choices=[('option1', 'Option 1'), ('option2', 'Option 2'), ('option3', 'Option 3')])),
            ],
        ),
        migrations.DeleteModel(
            name='millamaount',
        ),
    ]
