# Generated by Django 4.1.5 on 2023-01-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0007_mymodel_delete_millamaount'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='name',
            field=models.CharField(default='name', max_length=50),
        ),
    ]
