# Generated by Django 4.1.5 on 2023-01-26 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0009_meal_delete_mymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='name',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
