# Generated by Django 4.1.5 on 2023-01-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0010_meal_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='name',
        ),
        migrations.AddField(
            model_name='meal',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='person_1_meal',
            field=models.IntegerField(default=0, verbose_name=[('meal_1', 'meal_1'), ('meal_2', 'meal_2'), ('meal_3', 'meal_3')]),
        ),
    ]
