# Generated by Django 4.1.5 on 2023-01-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0012_remove_meal_parson_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='person_1_meal',
            field=models.IntegerField(default=0, verbose_name=[(1, 'meal_1'), (2, 'meal_2'), (3, 'meal_3')]),
        ),
    ]
