# Generated by Django 4.1.5 on 2023-01-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0014_alter_meal_person_1_meal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='person_1_meal',
            field=models.IntegerField(default=0, verbose_name=[('1', '1'), ('2', '2'), ('3', '3')]),
        ),
    ]
