# Generated by Django 4.1.5 on 2023-01-30 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0015_alter_meal_person_1_meal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='person_1_meal',
        ),
        migrations.AddField(
            model_name='meal',
            name='person_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meal',
            name='person_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meal',
            name='person_3',
            field=models.IntegerField(default=0),
        ),
    ]
